require: rubocop-rspec

AllCops:
  Exclude:
    - eqn.gemspec
    - Appraisals
    - vendor/**/*
  NewCops: enable

Layout/LineLength:
  Max: 130
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
Style/StringLiterals:
  Exclude:
    - gemfiles/*
