AllCops:
  Exclude:
    - eqn.gemspec
    - Appraisals
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
