AllCops:
  Exclude:
    - eqn.gemspec
    - Appraisals
    - lib/grammar/eqn.rb
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
